# 1. Import numpy as np and print the version number

In [1]:
import numpy as np
a=np.version
a

<module 'numpy.version' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>

# 2. Create a 1D array of numbers from 0 to 9

In [2]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 3. Create a 3×3 numpy array of all True’s(1's)

In [11]:
d=np.ones((3,3))
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 4. Convert a 1D array to a 2D array with 2 rows

In [5]:
a1=np.arange(6)
a1.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

# 5. Write a NumPy program to generate six random integers between 10 and 30

In [6]:
b=np.random.randint(10,30,6)
b

array([27, 29, 11, 11, 12, 23])

# 6. Write a NumPy program to create a 3x3x3 array with random values

In [9]:
c=np.random.randn(3,3,3)
c

array([[[ 2.02266472, -0.19374826, -1.03653118],
        [ 0.04785362,  0.19335021,  0.73859827],
        [-0.52487087,  0.00780765, -0.78245933]],

       [[ 0.17499873, -1.82531631,  0.5640999 ],
        [-0.1306868 ,  1.13186081, -1.06613758],
        [ 0.21336868,  0.07283594, -1.02114484]],

       [[ 0.06905073,  0.2241362 , -0.78233451],
        [ 1.04097471,  1.36179534, -2.57810739],
        [-0.33479416, -1.23486767,  0.78391464]]])

# 7.Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values

In [12]:
e=np.random.randn(5,5)
print(e)
mini=e.min()
maxi=e.max()
print(mini)
print(maxi)

[[-1.09527878 -1.07398599 -0.76879593 -0.34922734  0.23579234]
 [ 1.26070392  0.21738033  1.17030429  0.5086524  -0.3671393 ]
 [ 0.99779455 -0.57462711  0.65824411  1.32860043 -0.0611062 ]
 [ 0.51663974  0.64398144 -0.61900048  0.82276022  0.41197547]
 [-0.05012197  0.88771071 -0.19303313  1.43775566 -0.00893722]]
-1.0952787789939857
1.4377556561831952


# 8 Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable

In [23]:
f=np.random.randn(10,4)
print(f)
g=np.split(f,[5])
g

[[-1.71809158 -1.25018732  2.59566589 -1.53704393]
 [ 0.3540681   0.15179786 -1.71607214 -0.58287508]
 [-3.02602607 -0.7525833   0.28296772 -1.69126457]
 [-0.40644737 -1.16873644  1.5416283   0.68222022]
 [ 2.06178781 -0.62487866 -0.46298168  1.25286225]
 [-0.94055232 -0.43910013 -0.25215631  0.32534614]
 [ 0.03350268 -0.57200146 -1.4003185  -0.48558299]
 [ 0.50593826 -0.60794389 -0.42900376  1.2133132 ]
 [-0.7657191   0.0329503   0.52507654  1.97944006]
 [ 0.67648648  0.24209978  0.53316907  1.86288187]]


[array([[-1.71809158, -1.25018732,  2.59566589, -1.53704393],
        [ 0.3540681 ,  0.15179786, -1.71607214, -0.58287508],
        [-3.02602607, -0.7525833 ,  0.28296772, -1.69126457],
        [-0.40644737, -1.16873644,  1.5416283 ,  0.68222022],
        [ 2.06178781, -0.62487866, -0.46298168,  1.25286225]]),
 array([[-0.94055232, -0.43910013, -0.25215631,  0.32534614],
        [ 0.03350268, -0.57200146, -1.4003185 , -0.48558299],
        [ 0.50593826, -0.60794389, -0.42900376,  1.2133132 ],
        [-0.7657191 ,  0.0329503 ,  0.52507654,  1.97944006],
        [ 0.67648648,  0.24209978,  0.53316907,  1.86288187]])]

# 9.How to reverse the rows of a 2D array?

In [28]:
h= np.array([[1,2,3], [2,3,4], [3,4,5]])
i=np.flip(h,axis=0)
i

array([[3, 4, 5],
       [2, 3, 4],
       [1, 2, 3]])

# 10. Create 1D array with random numbers and replace all odd numbers in arr with -1

In [43]:
j=np.arange(10)
for i in range(len(j)):
    if j[i]%2!=0:
        j[i]=-1
print(j)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
